version: '3.8'

services:
  # VERİ TOPLAYICI (Arka Planda Sürekli Çalışır)
  solar-collector:
    container_name: solar_collector
    build: .
    entrypoint: ["python", "collector.py"]
    volumes:
      - ./solar_log.db:/app/solar_log.db
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  # ARAYÜZ (Sadece İzleme Yapar)
  solar-monitor:
    container_name: solar_monitor_pro
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./solar_log.db:/app/solar_log.db
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - solar-collector
    environment:
      - PYTHONUNBUFFERED=1