version: '3.8'

services:
  # VERİ TOPLAYICI (Yazan Servis)
  solar-collector:
    container_name: solar_collector
    build: .
    entrypoint: ["python", "collector.py"]
    volumes:
      - ./data:/app/data  # <--- BURASI KRİTİK: Dışarıdaki 'data' klasörünü içeriye bağlıyoruz
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

  # ARAYÜZ (Okuyan Servis)
  solar-monitor:
    container_name: solar_monitor_pro
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data  # <--- BURASI DA AYNI OLMALI: Panel de aynı klasörü okumalı
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - solar-collector
    environment:
      - PYTHONUNBUFFERED=1